name: why
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  flutter:
    sdk: flutter

  # reads svg icons
  flutter_svg: ^2.2.3
  firebase_core: ^3.10.0
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/icons/

  fonts:
      - family: Poppins
        fonts:
          - asset: fonts/Poppins-Regular.ttf
            weight: 400
          - asset: fonts/Poppins-Bold.ttf
            weight: 700
          - asset: fonts/Poppins-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: fonts/Poppins-LightItalic.ttf
            weight: 300
            style: italic
