// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxconWb0gQj9VeIJDYiwnWkZcafoEDsuU',
    appId: '1:635607867842:web:49472786407db97205365b',
    messagingSenderId: '635607867842',
    projectId: 'activity-4-f2dac',
    authDomain: 'activity-4-f2dac.firebaseapp.com',
    storageBucket: 'activity-4-f2dac.firebasestorage.app',
    measurementId: 'G-R7JCFBDEE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0iTC1ZhuSba2APvVgj-RV1uRRufeMI9w',
    appId: '1:635607867842:android:2bfcdb090a44498f05365b',
    messagingSenderId: '635607867842',
    projectId: 'activity-4-f2dac',
    storageBucket: 'activity-4-f2dac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVPkgWD8T4MuMItBbmFoaYh2ZJbLyr0CA',
    appId: '1:635607867842:ios:28dff8c83ef450e505365b',
    messagingSenderId: '635607867842',
    projectId: 'activity-4-f2dac',
    storageBucket: 'activity-4-f2dac.firebasestorage.app',
    iosBundleId: 'com.example.why',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVPkgWD8T4MuMItBbmFoaYh2ZJbLyr0CA',
    appId: '1:635607867842:ios:28dff8c83ef450e505365b',
    messagingSenderId: '635607867842',
    projectId: 'activity-4-f2dac',
    storageBucket: 'activity-4-f2dac.firebasestorage.app',
    iosBundleId: 'com.example.why',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxconWb0gQj9VeIJDYiwnWkZcafoEDsuU',
    appId: '1:635607867842:web:ce41d6929832036405365b',
    messagingSenderId: '635607867842',
    projectId: 'activity-4-f2dac',
    authDomain: 'activity-4-f2dac.firebaseapp.com',
    storageBucket: 'activity-4-f2dac.firebasestorage.app',
    measurementId: 'G-5VTYPBK08L',
  );
}
